version: '3.8'

services:
  tracklist:
    build: .
    container_name: tracklist-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/tracklist.db
      - LOG_LEVEL=INFO
      - ENABLE_FILE_LOGGING=true
      - LOG_FILE=logs/tracklist.log
      # Cache cleanup configuration
      - CACHE_CLEANUP_ENABLED=true
      - CACHE_CLEANUP_SCHEDULE=daily
      - CACHE_CLEANUP_TIME=03:00
      - CACHE_RETENTION_DAYS=365
      - CACHE_MAX_SIZE_MB=5000
      - CACHE_CLEANUP_DRY_RUN=false
      # Memory cache clear configuration  
      - MEMORY_CACHE_CLEAR_ENABLED=true
      - MEMORY_CACHE_CLEAR_SCHEDULE=weekly
      - MEMORY_CACHE_CLEAR_DAY=sunday
      - MEMORY_CACHE_CLEAR_TIME=04:00
      # Reports configuration
      - REPORTS_ENABLED=true
      - REPORTS_SCHEDULE=weekly
      - REPORTS_DAY=monday
      - REPORTS_TIME=09:00
      # Artwork migration configuration
      - AUTO_MIGRATE_ARTWORK=true
      - MIGRATION_BATCH_SIZE=10
      - MIGRATION_MAX_ALBUMS=0
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./static/artwork_cache:/app/static/artwork_cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s